config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controller: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  get '/howto', to: 'home#howto'
  get '/user/:id', to: 'user#show'
  resources :vehicles do
    collection do
      get :automobiles
      get :boats
      get :motorcycles
    end
    resources :photos, only: :create
  end
  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/automobile.rb
class Automobile < Vehicle
end

app/models/boat.rb
class Boat < Vehicle
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id
  
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)",
    sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/motorcycle.rb
class Motorcycle < Vehicle
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :vehicle
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  has_many :vehicles
  has_many :conversations
  has_many :messages
  has_many :user_reviews
  validates :first_name, presence: :true
  validates :last_name, presence: :true
  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_h).first
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end
end

app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :for_user, class_name: 'User'
  belongs_to :by_user, class_name: 'User'

  scope :reviews_for, ->(user) { where(for_user: user) }
  scope :reviews_by,  ->(user) { where(by_user: user) }
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  validates :type, :make, :model, :color, :year, :mileage, :price, presence: :true
  before_save :capitalize_make, :capitalize_model, :capitalize_color
  has_many :photos

  def capitalize_make
    self.make = self.make.capitalize
  end

  def capitalize_model
    self.model = self.model.capitalize
  end

  def capitalize_color
    self.color = self.color.capitalize
  end

  def self.search(term)
    if term
      where('UPPER(model) LIKE :search OR
             UPPER(make) LIKE :search OR
             UPPER(color) LIKE :search OR
             UPPER(description) LIKE :search', search: term.upcase)
    else
      all
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def howto
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
   @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
      if @messages.length > 10
        @over_ten = true
        @messages = @messages[-10..-1]
      end
      if params[:m]
        @over_ten = false
        @messages = @conversation.messages
      end
    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.last.read = true;
      end
    end
    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

private

  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
    @vehicle.photos.create!(photo_params)
    redirect_to vehicle_path(@vehicle)
  end

  private

  def photo_params
    params.require(:photo).permit(:picture)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @vehicles = Vehicle.search(params[:term])
  end

  def automobiles
    @vehicles = Vehicle.where(type: 'Automobile')
    render "vehicles/index"
  end

  def boats
    @vehicles = Vehicle.where(type: 'Boat')
    render "vehicles/index"
  end

  def motorcycles
    @vehicles = Vehicle.where(type: 'Motorcycle')
    render "vehicles/index"
  end

  def show
    @photo = Photo.new
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = current_user.vehicles.create(vehicle_params)
    redirect_to vehicles_path(@vehicle)
  end

  def update
    current_vehicle.update_attributes(lesson_params)
    redirect_to vehicles_path(current_vehicle)
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy
    redirect_to vehicles_path
  end

  private

  helper_method :current_vehicle

  def vehicle_params
    params.require(:vehicle).permit(:type, :make, :model, :color, :year, :mileage, :price, :description, :term)
  end

  def current_vehicle
    @current_vehicle ||= Vehicle.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vehicle_helper.rb
module VehicleHelper
end

app/views/messages/index.html.erb
<% if @over_ten %>
  <%= link_to 'Show Previous', '?m=all' %>
<% end %>
<div class="ui segment">
  <% @messages.each do |message| %>
    <% if message.body %>
      <% user = User.find(message.user_id) %>
      <div class="item">
        <div class="content">
          <div class="header"><strong><%= user.first_name %></strong> <%= message.message_time %></div>
          <div class="list">
            <div class="item">
              <i class="right triangle icon"></i>
                <%= message.body %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= form_for [@conversation, @message], html: {class: "ui reply form"} do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
  <div>
    <%= f.submit "Add Reply", class: "ui blue labeled submit icon button" %>
  </div>
<% end %>

app/views/messages/show.html.erb
<% if @over_ten %>
  <%= link_to 'Show Previous', '?m=all' %>
<% end %>
<div class="ui segment">
  <% @messages.each do |message| %>
    <% if message.body %>
      <% user = User.find(message.user_id) %>
      <div class="item">
        <div class="content">
          <div class="header"><strong><%= user.first_name %></strong> <%= message.message_time %></div>
          <div class="list">
            <div class="item">
              <i class="right triangle icon"></i>
                <%= message.body %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= form_for [@conversation, @message], url: conversations_message_path(@conversation), html: {class: "ui reply form"} do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
  <div>
    <%= f.submit "Add Reply", class: "ui blue labeled submit icon button" %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<div class="container">
  </br>
  <h1>Edit Vehicle</h1>
  </br>
  <%= simple_form_for @vehicle do |f| %>
    <%= f.input :type, collection: [ "Automobile", "Motorcycle", "Boat" ], selected: @vehicle.type %>
    <div class="row">
      <div class="col">
        <%= f.input :make, hint: false, placeholder: @vehicle.make %>
      </div>
      <div class="col">
        <%= f.input :model, hint: false, placeholder: @vehicle.model %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= f.input :color, hint: false, placeholder: @vehicle.color %>
      </div>
      <div class="col">
        <%= f.input :year, hint: false, placeholder: @vehicle.year %>
      </div>
    </div>
    <%= f.input :mileage, label: "Mileage (km)", hint: false, placeholder: @vehicle.mileage %>
    <%= f.input :price, input_html: {maxlength: 10 }, hint: false, placeholder: @vehicle.price %>
    <%= f.input :description, placeholder:@vehicle.description %>
    <%= f.submit 'Update', :class => "btn btn-secondary" %>
    <%= f.button :button, 'Reset', :type => 'reset', :class => 'btn btn-danger' %>
  <% end %>
</div>

app/views/vehicles/index.html.erb
<h1>Listings</h1>
<% @vehicles.each do |vehicle| %>
  <%= link_to "#{vehicle.year} #{vehicle.make} #{vehicle.model}", vehicle_path(vehicle) %>
  </br>
<% end %>

app/views/vehicles/new.html.erb
<div class="container">
  </br>
  <h1>List a Vehicle</h1>
  </br>
  <%= simple_form_for @vehicle do |f| %>
    <%= f.input :type, collection: [ "Automobile", "Motorcycle", "Boat" ], selected: "Automobile" %>
    <div class="row">
      <div class="col">
        <%= f.input :make, hint: false %>
      </div>
      <div class="col">
        <%= f.input :model, hint: false %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= f.input :color, hint: false %>
      </div>
      <div class="col">
        <%= f.input :year, hint: false %>
      </div>
    </div>
    <%= f.input :mileage, label: "Mileage (km)", hint: false %>
    <%= f.input :price, input_html: {maxlength: 10 }, hint: false %>
    <%= f.input :description %>
    <%= f.submit 'Post', :class => "btn btn-secondary" %>
    <%= f.button :button, 'Reset', :type => 'reset', :class => 'btn btn-danger' %>
  <% end %>
</div>

app/views/vehicles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <h2><%= current_vehicle.year %> <%= current_vehicle.make %> <%= current_vehicle.model %></h2>
    </div>
    <div class="col-2 text-center">
      <% if current_user == current_vehicle.user %>
        <%= button_to "Delete Listing", vehicle_path(current_vehicle), class: "btn btn-danger", style: "margin-top: 8px", method: :delete %>
      <% end %>
    </div>
  </div>
  <hr>
  Seller: <%= link_to current_vehicle.user.email, user_path(current_vehicle.user) %>
  <br />
  <br />
  <span class="listing-price">
    <b>Asking Price: <%= number_to_currency(current_vehicle.price) %></b>
  </span>
  <br />
  <br />
  <div class="specifications-box">
    <h3>Images</h3>
    <div class="row">
      <% current_vehicle.photos.each do |photo| %>
        <%= link_to image_tag(photo.picture.thumb.url), photo.picture.url, class: "photo" %>
      <% end %>
    </div>
    <hr />
    <h3>Specifications</h3>
    <div class="row">
      <div class="col-2">
        Model: <%= current_vehicle.color %>
      </div>
      <br />
      <div class="col-2">
        Mileage: <%= number_with_delimiter(current_vehicle.mileage) + " km" %>
      </div>
    </div>
    <hr />
    <h3>Additional Notes</h3>
    <%= current_vehicle.description %>
  </div>
  <% if current_user == current_vehicle.user %>
    <%= simple_form_for @photo, url: vehicle_photos_path(current_vehicle) do |f| %>
      <%= f.input :picture %>
      <%= f.submit "Add Photo", class: 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>