config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controller: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  get '/howto', to: 'home#howto'
  get '/user/:id', to: 'user#show'
  resources :vehicles do
    collection do
      get :automobiles
      get :boats
      get :motorcycles
    end
    resources :photos, only: :create
  end
  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/automobile.rb
class Automobile < Vehicle
end

app/models/boat.rb
class Boat < Vehicle
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id
  
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)",
    sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/motorcycle.rb
class Motorcycle < Vehicle
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :vehicle
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  has_many :vehicles
  has_many :conversations
  has_many :messages
  has_many :user_reviews
  validates :first_name, presence: :true
  validates :last_name, presence: :true
  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_h).first
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end
end

app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :for_user, class_name: 'User'
  belongs_to :by_user, class_name: 'User'

  scope :reviews_for, ->(user) { where(for_user: user) }
  scope :reviews_by,  ->(user) { where(by_user: user) }
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  validates :type, :make, :model, :color, :year, :mileage, :price, presence: :true
  before_save :capitalize_make, :capitalize_model, :capitalize_color
  has_many :photos

  def capitalize_make
    self.make = self.make.capitalize
  end

  def capitalize_model
    self.model = self.model.capitalize
  end

  def capitalize_color
    self.color = self.color.capitalize
  end

  def self.search(term)
    if term
      where('UPPER(model) LIKE :search OR
             UPPER(make) LIKE :search OR
             UPPER(color) LIKE :search OR
             UPPER(description) LIKE :search', search: term.upcase)
    else
      all
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @conversations = Conversation.where(sender_id: current_user.id).or(Conversation.where(recipient_id: current_user.id))
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],
                                           params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

  private
  
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def howto
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
   @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
      if @messages.length > 10
        @over_ten = true
        @messages = @messages[-10..-1]
      end
      if params[:m]
        @over_ten = false
        @messages = @conversation.messages
      end
    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.last.read = true;
      end
    end
    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

private

  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
    @vehicle.photos.create!(photo_params)
    redirect_to vehicle_path(@vehicle)
  end

  private

  def photo_params
    params.require(:photo).permit(:picture)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vehicle_helper.rb
module VehicleHelper
end

app/views/conversations/index.html.erb
<div class="ui segment">
  <h3>Conversations</h3>
  <div class="ui list">
    <div class="item">
      <% @conversations.each do |conversation| %>
        <% if conversation.sender_id == current_user.id %>
          <% recipient = User.find(conversation.recipient_id) %>
        <% else %>
          <% recipient = User.find(conversation.sender_id) %>
        <% end %>
        <%= link_to recipient.first_name, conversation_messages_path(conversation) %>        
      <% end %>
    </div>
  </div>
</div>
<div class="ui segment">
  <h3>All Users</h3>
  <div class="ui list">
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
        <div class="item">
          <%= user.first_name %> <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="ui segment">
  <h3>Conversations</h3>
  <div class="ui list">
    <div class="item">
      <% @conversations.each do |conversation| %>
        <% if conversation.sender_id == current_user.id %>
          <% recipient = User.find(conversation.recipient_id) %>
        <% else %>
          <% recipient = User.find(conversation.sender_id) %>
        <% end %>
        <%= link_to recipient.first_name, conversations_message_path(conversation) %>        
      <% end %>
    </div>
  </div>
</div>
<div class="ui segment">
  <h3>All Users</h3>
  <div class="ui list">
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
        <div class="item">
          <%= user.first_name %> <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
        </div>
      <% end %>
    <% end %>
  </div>
</div>