config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controller: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  get '/howto', to: 'home#howto'
  get '/user/:id', to: 'user#show'
  resources :vehicles do
    collection do
      get :automobiles
      get :boats
      get :motorcycles
    end
    resources :photos, only: :create
  end
  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/automobile.rb
class Automobile < Vehicle
end

app/models/boat.rb
class Boat < Vehicle
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id
  
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)",
    sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/motorcycle.rb
class Motorcycle < Vehicle
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :vehicle
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  has_many :vehicles
  has_many :conversations
  has_many :messages
  has_many :user_reviews
  validates :first_name, presence: :true
  validates :last_name, presence: :true
  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_h).first
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end
end

app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :for_user, class_name: 'User'
  belongs_to :by_user, class_name: 'User'

  scope :reviews_for, ->(user) { where(for_user: user) }
  scope :reviews_by,  ->(user) { where(by_user: user) }
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  validates :type, :make, :model, :color, :year, :mileage, :price, presence: :true
  before_save :capitalize_make, :capitalize_model, :capitalize_color
  has_many :photos

  def capitalize_make
    self.make = self.make.capitalize
  end

  def capitalize_model
    self.model = self.model.capitalize
  end

  def capitalize_color
    self.color = self.color.capitalize
  end

  def self.search(term)
    if term
      where('UPPER(model) LIKE :search OR
             UPPER(make) LIKE :search OR
             UPPER(color) LIKE :search OR
             UPPER(description) LIKE :search', search: term.upcase)
    else
      all
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def howto
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vehicle_helper.rb
module VehicleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Autoexchange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom: 0.5rem">
      <%= link_to (image_tag("autoexchange.png", height: '50', class: 'brand-icon mr-lg-5')), root_path %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if params[:action] == 'index' %>">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item <%= 'active' if params[:action] == 'howto' %>">
              <a class="nav-link" href="/howto">How To Exchange</a>
            </li>
            <li class="nav-item dropdown <%= 'active' if params[:controller] == 'vehicles' && params[:action] != 'new' %>">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Vehicles
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="/vehicles">All Vehicles</a>
                <a class="dropdown-item" href="/vehicles/automobiles">Automobiles</a>
                <a class="dropdown-item" href="/vehicles/motorcycles">Motorcycles</a>
                <a class="dropdown-item" href="/vehicles/boats">Boats</a>
              </div>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <a class="nav-link <%= 'active' if params[:controller] == 'vehicles' && params[:action] == 'new' %>" href="/vehicles/new">List a Vehicle</a>
              </li>
            <% end %>
          </ul>
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "My Profile", '#', class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Log in", new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          <%= form_tag(vehicles_path, method: :get, class: 'form-inline my-2 my-lg-0') do %>
            <%= text_field_tag :term, params[:term], class: 'form-control mr-sm-2' %>
            <%= submit_tag 'Search', name: nil, class: 'btn btn-outline-danger my-2 my-sm-0' %>
          <% end %>
        </div>
    </nav>
    <% if notice.present? %>
      <div class="alert alert-primary" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>